/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import com.intuit.karate.junit5.Karate;

public class AppTest {
    @Karate.Test
    Karate testLoginSignup() {
        return Karate.run("classpath:PetStore.feature").relativeTo(getClass());
    }
}
